services:
    laravel.test:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        volumes:
            - './:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
    nginx:
        image: 'nginx:latest'
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - './:/var/www/html'
            - './docker/nginx/conf.d:/etc/nginx/conf.d'
        networks:
            - sail
        depends_on:
            - laravel.test
    mysql:
        image: 'mysql:8'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - './docker/volume/mysql:/var/lib/mysql'
        networks:
            - sail
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '9090:80'
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
